name: sync

on:
  workflow_run:
    workflows:
      - bundle
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: https://gitlab.com/novi028/JS-Slash-Runner.git
          username: novi028
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
          force_push: true
